apiVersion: v1
kind: Service
metadata:
  name: gone
  annotations:
    external-dns.alpha.kubernetes.io/hostname: default-gone.autok8s.raidancampbell.com
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: gone
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gone
  name: gone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gone
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: gone
    spec:
      containers:
      - env:
        - name: REDIS_ADDR
          value: redis:6379
        image: localhost:5000/gone
        imagePullPolicy: "Always"
        livenessProbe: &probe
          initialDelaySeconds: 1
          httpGet:
            port: 8080
            path: /alive
        readinessProbe: *probe
        name: gone-container
        ports:
        - containerPort: 8080
        resources:
          requests:
              cpu: 100m
              memory: 200Mi
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:6.0.8
        imagePullPolicy: "IfNotPresent"
        name: redis-container
        ports:
        - containerPort: 6379
      restartPolicy: Always
