apiVersion: v1
kind: Service
metadata:
  name: gone
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: gone
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gone
  name: gone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gone
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: gone
    spec:
      containers:
      - env:
        - name: REDIS_ADDR
          value: redis:6379
        image: localhost:5000/gone
        imagePullPolicy: "Always"
        livenessProbe: &probe
          initialDelaySeconds: 1
          httpGet:
            port: 8080
            path: /alive
        readinessProbe: *probe
        name: gone-container
        ports:
        - containerPort: 8080
        resources:
          requests:
              cpu: 100m
              memory: 200Mi
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:6.0.8
        imagePullPolicy: "IfNotPresent"
        name: redis-container
        ports:
        - containerPort: 6379
      restartPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gone-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: gone.k8s.nuc.raidancampbell.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gone
                port:
                  number: 8080
#---
#apiVersion: extensions/v1beta1
#kind: NetworkPolicy
#metadata:
#  creationTimestamp: null
#  name: backend
#spec:
#  ingress:
#  - from:
#    - podSelector:
#        matchLabels:
#          io.kompose.network/backend: "true"
#  podSelector:
#    matchLabels:
#      io.kompose.network/backend: "true"
